### ISSUE TITLE
Create new request

### ISSUE THREAD

**Issue by petelc** [petelc/work-management-system#47]
The create new request no longer works. The request types and requestors are not setup correctly for the api.

### Tasks

- [ ] Request Types need to send the request type id and the name
- [ ] Requestors is not pulling the employee thus not creating the relationship correctly.
- [ ] API needs to accept all of the data being sent and process creating the required relationship objects
- [ ] React app needs to collect all of the submitted data in the correct format.
- [ ] I need to capture the employee id when registering a new user 
- [ ] On the create request form we need to pass the employee id to the api as part of the array of requestors.
